version: "3"
services:
  server_mainnet:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_CONNECTION=postgres://public_readonly:nearprotocol@104.199.89.51/mainnet_explorer
  server_testnet:
    build: .
    ports:
      - "3001:3000"
    environment:
      - DB_CONNECTION=postgres://public_readonly:nearprotocol@35.184.214.98/testnet_explorer
